import React,{useEffect,useMemo,useState} from 'react';import{createRoot}from'react-dom/client';import'./style.css';
type Log={id?:string;log_time:string;host:string;source_type:string;source_name:string;category?:string;level?:string;message:string;metadata?:unknown};
const API=import.meta.env.VITE_API_URL||'';
function App(){const[logs,setLogs]=useState<Log[]>([]),[category,setCategory]=useState(''),[level,setLevel]=useState(''),[host,setHost]=useState(''),[keyword,setKeyword]=useState(''),[categories,setCategories]=useState<string[]>([]),[connected,setConnected]=useState(false);
 const load=async()=>{const p=new URLSearchParams({limit:'200'});if(category)p.set('category',category);if(level)p.set('level',level);if(host)p.set('host',host);if(keyword)p.set('keyword',keyword);try{const r=await fetch(`${API}/api/logs?${p}`);if(r.ok){const d=await r.json();setLogs(Array.isArray(d)?d:(d.logs||[]))}}catch{}};
 useEffect(()=>{fetch(`${API}/api/logs/categories`).then(r=>r.json()).then(d=>setCategories(Array.isArray(d)?d:(d.categories||[]))).catch(()=>{});load()},[]);
 useEffect(()=>{const proto=location.protocol==='https:'?'wss':'ws';const url=API?`${API.replace(/^http/,'ws')}/api/logs/ws`:`${proto}://${location.host}/api/logs/ws`;let ws:WebSocket;try{ws=new WebSocket(url);ws.onopen=()=>setConnected(true);ws.onclose=()=>setConnected(false);ws.onmessage=e=>{try{const l=JSON.parse(e.data);setLogs(x=>[l,...x].slice(0,200))}catch{}}}catch{}return()=>ws?.close()},[]);
 const filtered=useMemo(()=>logs.filter(l=>(!category||l.category===category)&&(!level||l.level===level)&&(!host||l.host===host)&&(!keyword||l.message.toLowerCase().includes(keyword.toLowerCase()))),[logs,category,level,host,keyword]);
 return <div className="app"><header><div><h1>LogHub</h1><span>日志采集与实时查询平台</span></div><div className={connected?'ok':'bad'}>● {connected?'实时连接':'未连接'}</div></header><section className="filters"><input placeholder="主机" value={host} onChange={e=>setHost(e.target.value)}/><select value={category} onChange={e=>setCategory(e.target.value)}><option value="">全部分类</option>{categories.map(c=><option key={c}>{c}</option>)}</select><select value={level} onChange={e=>setLevel(e.target.value)}><option value="">全部级别</option><option>error</option><option>warning</option><option>info</option><option>debug</option></select><input className="keyword" placeholder="搜索日志内容" value={keyword} onChange={e=>setKeyword(e.target.value)}/><button onClick={load}>查询</button></section><main><aside><h3>日志分类</h3><button className={!category?'active':''} onClick={()=>setCategory('')}>全部</button>{categories.map(c=><button className={category===c?'active':''} key={c} onClick={()=>setCategory(c)}>{c}</button>)}</aside><section className="logs"><div className="count">实时日志 · {filtered.length} 条</div>{filtered.map((l,i)=><article key={l.id||i} className={l.level==='error'?'error':''}><div className="meta"><time>{new Date(l.log_time).toLocaleString()}</time><b>{l.host}</b><span>{l.source_type}/{l.source_name}</span><em>{l.level||'info'}</em></div><div className="message">{l.message}</div></article>)}</section></main></div>};createRoot(document.getElementById('root')!).render(<App/>);
